### ISSUE TITLE
NullPointerException: Rendering screen, What is causing this crash

### ISSUE THREAD

**Issue by Kylebartaous** [Darkhax-Minecraft/WAWLA#90] opened 2018-04-14 05:27 UTC
Mine craft: 1.12.2
Forge build: 14.23.3.2667 w/ lite loader installed
Wawla: 2-2.5.253
Hwyla: 1.8.24-b39
Waila harvest-ability:
Tumat: 
World tool tip: 
Jei: 2-4.8.5.159 + some addons it has

I am crashing then selecting / scrolling over a water bucket in my hot bar & possible then i try to pick up and place down water w/ said water bucket,I have tried to reinstall and clear the configs for those mods to see if if was something easy like that to fix it,

The logs and crash logs: 

[crash-2018-04-14_00.06.32-client.txt](https://github.com/Darkhax-Minecraft/WAWLA/files/1910040/crash-2018-04-14_00.06.32-client.txt)

**Comment by darkhax** [comment] 2018-04-14 16:48
Thanks for reporting this, it seems like a duplicate of this issue, however the poster deleted it before I could comment on things. https://github.com/Darkhax-Minecraft/WAWLA/issues/89

I am going to look into this issue a bit more today, but it seems like it may actually be an issue with Forge. Thanks again for reporting, I will update when I have more info.

**Comment by Kylebartaous** [comment] 2018-04-16 18:34
Updating forge build seems to had fixed it , any build past 14.23.3.2666

**Closed** 2018-04-16 18:37 UTC
